# Generated by Django 4.2.7 on 2024-01-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formsapp", "0002_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="formsapp.teacher",
            ),
        ),
    ]
